# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [14]:
A = np.arange(1, 16).reshape(3,5)

A.ndim 
print("Dimensionen av matrix A är:", A.ndim)
A.shape
print("Array har:", A.shape)
A.size      
print("Totalt element i array:", A.size)
A.dtype
print("Datatype:", A.dtype)


Dimensionen av matrix A är: 2
Array har: (3, 5)
Totalt element i array: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [19]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)
print()

resultat = B - C
print("Substraktion:","\n", resultat)
print()

Multiplikation = B * C
print("Multiplikation:","\n", Multiplikation)
print()

Matris_resultat = B @ C
print("Matris multiplikation:","\n", Matris_resultat)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Substraktion: 
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Multiplikation: 
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matris multiplikation: 
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [20]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# Exponentiate each number elementwise. 
resultat = np.exp(B)
print(resultat)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [22]:
# Calculate the minimun value in whole matrix 
my_matrix = np.min(B)
print("The minimun value is:", my_matrix)

The minimun value is: 1


In [31]:
 # The minimun value in each row.
B = np.arange(1, 10).reshape(3, 3)
print(B)
my_value = B.min(axis = 1)
print("The minimun value in each row is:", my_value)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The minimun value in each row is: [1 4 7]


In [32]:
# The minimun value in each column.
B.min(axis = 0)

array([1, 2, 3])

In [38]:
# The index value for the minimum value in the matrix.
B = np.arange(1, 10).reshape(3, 3)
print(B)

min_value = np.argmin(B)
print("Index:", min_value)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Index: 0


In [44]:
# Sum for all element.
B.sum()

np.int64(45)

In [48]:
# The mean for each column.
column_m = np.mean(B, axis = 0)
print("The mean for each column:", column_m)

The mean for each column: [4. 5. 6.]


In [46]:
# The median
median_column = np.median(B, axis = 0)
print("The median for each column:", median_column)

The median for each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [49]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [50]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
# Slicing är ett sätt att extrahera delar av en array,
# vi kan göra detta genom skriva array[1] eller i det här fallet A[1].
# Koden har hämtat hela den andra raden i array A[1].

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [51]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [52]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [64]:
for i in np.nditer(A):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [65]:
a = np.arange(30)  # skapar en matris/array med värden från 0 till 30, men det inte inkl. 30. 
b = a.reshape((2, 3, -1)) # används för att ändra formen på array, utan ändra data. Koden ska skapa 2 block med 3 dimensioner.
                          # -1 ska räkna ut storleken på b baserat på elementer som finns i array a. 
  
print(a)    #Skriver ut elementer på array a.
print()

print(b) # Ska skriva ut 2 block med 3 axis, utan ändra data i den ursprungliga arrayen. 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [13]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)


[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [14]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [18]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)
print()

print(A + b)
print()

print(A * b)

[[1 2]
 [3 4]]
[2 2]

[[3 4]
 [5 6]]

[[2 4]
 [6 8]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [27]:
def add_mult_matrices(matrix1, matrix2, operationer):
    
    """Addition and multiplication in two matrices,
    
    Parameter: 
    matrix1 (numpy.ndarray): The fist matrix
    matris2 (numpy.ndarray): The second matrix.
    operationer (str): Either 'add' or 'multiply' 
    
    Returns:
    numpy.ndarray: The result of the operation.
    
    Raises:
    ValueError: If input values are incorrect or if the size of dimensions are not equal."""
    
    if not isinstance (matrix1, np.ndarray) or not isinstance (matrix2, np.ndarray):
        raise ValueError("Both input must be of type numpy.ndarray")
    if operationer not in ["add", "multiply"]:
        raise ValueError("Operationer must be add or multiply")
    
    if operationer == "add": 
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrix1 and matrix2 must have the same dimensions for addition")
        return matrix1 + matrix2
    
    if operationer == "multiply":
        if matrix1.shape != matrix2.shape:
            raise ValueError("Number of columns in Matrix1 must be equal to the number of rows in matrix2.")
        return np.dot(matrix1, matrix2)
    
    A = np.array([2,4],[1,6])
    B = np.array([4,2],[3,4])
    
    add_result = add_mult_matrices (A, B, "add")
    print("Sum of matrices:\n", add_result)
    
    mult_result = add_mult_matrices (A,B, "multiply")
    print("Multiplication of matrices:\n", mult_result)
        
        

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [28]:
import numpy as np

# Uppgift 10.1.1. Definera vektorn x

x = np.array([4,3])
dimension = x.ndim
print("dimension av x är", dimension) 

print("5x =", 5*x)
print("3x =", 3*x)
print("5x + 3x =", 5*x + 3*x)
print("8x =", 8*x)
print("4x - x =", 4*x - x)

#Beräkna nya dimensionen efter att transporterings utförs.

x_transpoded = x.T
print("x^T =", x_transpoded)
print("Dimensionen efter transponering blir:", x_transpoded.shape[0])

# Beräkna ||x||
norm_x = np.linalg.norm(x)
print("Avståndet mellan de två vektorer är:", norm_x) 


dimension av x är 1
5x = [20 15]
3x = [12  9]
5x + 3x = [32 24]
8x = [32 24]
4x - x = [12  9]
x^T = [4 3]
Dimensionen efter transpornering blir: 2
Avståndet mellan de två vektorer är: 5.0


In [40]:
# Definiera vektorn v enligt nedan:

v = np.array([3,7,0,11])
dimension = v.shape[0]
print("dimension av vektorn v är:", dimension)

print("2v =", 2*v)
print("5v + 2v =", 5*v + 2*v)
print("4v - 2v =", 4*v -2*v)


#Beräkna v^T, vilken blir den nya dimensionen efter att transponeringen utförts?
v_transpoded = v.T
print("Dimensionen efter transponering blir:", v_transpoded.shape[0])

#Beräkna ||v||

norm_v = np.linalg.norm(v)
print("Norm av v:", norm_v)


dimension av vektorn v är: 4
2v = [ 6 14  0 22]
5v + 2v = [21 49  0 77]
4v - 2v = [ 6 14  0 22]
Dimensionen efter transponering blir: 4
Norm av v: 13.379088160259652


In [49]:
# Beräkna 10.1.3 Definera vektorerna v1 = (4,3,1,5) och v2= (2,3,1,1)

v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])

norm_v1 = np.linalg.norm(v1)
print("Norm av v1:", norm_v1)

# Beräkna ||v1-v2||
v_subtraktion=  v1 - v2
print("Beräkning av v1-v2 blir:", v_subtraktion)

norm_subtraktion = np.linalg.norm(v_subtraktion)
print("Normen av v1 - v2 är:", norm_subtraktion)



Norm av v1: 7.14142842854285
Beräkning av v1-v2 blir: [2 0 0 4]
Normen av v1 - v2 är: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [15]:
# Uppgifter 10.2.1. Definiera matriserna:

A = np.array([2, 1, -1, 1, -1, 1])
B = np.array([4, -2, 1, 2, -4, -2])
C = np.array([1, 2, 2, 1])
D = np.array([3, 4, 4, 3])
E = np.array([1, 2])
I = np.array([1, 0, 0, 1])

print("2A =", 2*A)
print("B -2A =", B - 2*A)
print("3C - 2E = är ej definerat")
print("2D - 3C =", 2*D - 3*C)
print("D^T + 2D =", D.T + 2*D)
print("2C^T - 2D^T =", 2*C.T - 2*D.T)
print("A^T - B =", A.T - B)
print("AC = är ej definerat")
print("CD =", C*D)
print("CB = är ej definerat. Antalet kolumner i C inte matchar antalet rader i B.")
print("CI =", C*I)
print("AB^T =", A*B.T)


2A = [ 4  2 -2  2 -2  2]
B -2A = [ 0 -4  3  0 -2 -4]
3C - 2E = är ej definerat
2D - 3C = [3 2 2 3]
D^T + 2D = [ 9 12 12  9]
2C^T - 2D^T = [-4 -4 -4 -4]
A^T - B = [-2  3 -2 -1  3  3]
AC = är ej definerat
CD = [3 8 8 3]
CB = är ej definerat. Antalet kolumner i C inte matchar antalet rader i B.
CI = [1 0 0 1]
AB^T = [ 8 -2 -1  2  4 -2]


In [29]:
# Uppgift 10.2.2. Definiera matrisen.

A = np.array([2, 3, 4, 5, 4, 1])
print(A*A.T)



[ 4  9 16 25 16  1]


In [39]:
# Uppgift 10.2.3. definiera matriserna.
A = np.array ([1, 2, 2, 4]) 
B = np.array([2, 1, 1, 3]) 
C = np.array([4, 3, 0, 2])

AB = np.dot(A, B)
AC = np.dot(A, C)

#Resultat
compare_ = np.array_equal(AB, AC)
print("AB = AC:", compare_)




AB = AC: True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [41]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [43]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [ ]:
# Svar: När man använder .base och det blir "none" det betyder att arrayen är en kopia. Om det är en annan array, så är det view av en array. 


In [45]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
